// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apilocadora.Data.Models;

namespace apilocadora.Migrations
{
    [DbContext(typeof(AppEfCoreDbContext))]
    [Migration("20220221205146_data seeding")]
    partial class dataseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apilocadora.Data.Models.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("fe563ad4-a27a-4a88-8470-d594b9fdec6f"),
                            Email = "mikhail.tal@mail.com",
                            PasswordHash = "$2b$10$R0uMrUQBN3RNUgIFrZWZEOO4O7Cw8L3a3FWmvE1mr4i1lRTEM.S7u"
                        },
                        new
                        {
                            IdUser = new Guid("3e10442e-e9cb-4f86-9531-c45cc5564dbb"),
                            Email = "tigran.petrosian@mail.com",
                            PasswordHash = "$2b$10$KRguMdIx/ewjPBy4NN6o2.3W0rI9nXI7uQJmQs/uNEr0DKSSurTaO"
                        },
                        new
                        {
                            IdUser = new Guid("4e625a98-90a4-44a7-99b6-8a304802d19b"),
                            Email = "hikaru.nakamura@mail.com",
                            PasswordHash = "$2b$10$q1x6yp9ft9aLNE6awkTHGeSU/.IWz2FaYhBqOsmFZ3FghzkJszszq"
                        },
                        new
                        {
                            IdUser = new Guid("025e20d1-c141-491a-ad77-127452cd3ef9"),
                            Email = "garry.kasparov@mail.com",
                            PasswordHash = "$2b$10$4WArT4wGuT00Z8bIjaAeL.CuIIbW8es4hOMr1VswLCYjAuvGtFMZm"
                        });
                });

            modelBuilder.Entity("apilocadora.Data.Models.Veiculo", b =>
                {
                    b.Property<Guid>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVeiculo");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            IdVeiculo = new Guid("ca0589d9-44f0-4bfc-b426-cc0d5aedba3a"),
                            Categoria = "Passeio",
                            Modelo = "Onix"
                        },
                        new
                        {
                            IdVeiculo = new Guid("de03f01a-7c75-40c7-a70d-bfb30eab47f6"),
                            Categoria = "Utilitario",
                            Modelo = "Fiat Toro"
                        },
                        new
                        {
                            IdVeiculo = new Guid("348bd7b7-3224-4da6-bd70-39ebc6a075f9"),
                            Categoria = "Luxo",
                            Modelo = "Ferrari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
